### ISSUE TITLE
Does not work with Cytoscape's included version of Xerces

### ISSUE THREAD

**Issue by stuppie** [stuppie/WikiDataScape#10]
java.lang.VerifyError: (class: org/apache/xerces/impl/dv/xs/AbstractDateTimeDV, method: signature: ()V) Bad type in putfield/putstatic
at org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl.(Unknown Source)
at org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl.createBuiltInTypes(Unknown Source)
at org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl.(Unknown Source)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at org.apache.xerces.impl.dv.ObjectFactory.newInstance(Unknown Source)
at org.apache.xerces.impl.dv.SchemaDVFactory.getInstance(Unknown Source)
at org.apache.xerces.impl.dv.SchemaDVFactory.getInstance(Unknown Source)
at com.hp.hpl.jena.datatypes.xsd.XSDDatatype.(XSDDatatype.java:230)
at com.hp.hpl.jena.datatypes.xsd.XSDDatatype.(XSDDatatype.java:242)
at com.hp.hpl.jena.datatypes.xsd.impl.XSDFloat.(XSDFloat.java:49)
at com.hp.hpl.jena.datatypes.xsd.XSDDatatype.(XSDDatatype.java:63)
at com.hp.hpl.jena.sparql.expr.nodevalue.XSDFuncOp.(XSDFuncOp.java:766)
at com.hp.hpl.jena.query.ARQ.setNormalMode(ARQ.java:381)
at com.hp.hpl.jena.query.ARQ.defaultSettings(ARQ.java:463)
at com.hp.hpl.jena.query.ARQ.init(ARQ.java:438)
at com.hp.hpl.jena.query.ARQ.(ARQ.java:458)
at org.apache.jena.riot.RIOT.(RIOT.java:38)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at com.hp.hpl.jena.rdf.model.impl.IO_Ctl.callByRefection(IO_Ctl.java:54)
at com.hp.hpl.jena.rdf.model.impl.IO_Ctl.init(IO_Ctl.java:36)
at com.hp.hpl.jena.rdf.model.impl.ModelCom.(ModelCom.java:65)
at com.hp.hpl.jena.rdf.model.ModelFactory.createDefaultModel(ModelFactory.java:140)
at org.cytoscape.vsdl3c.internal.SPARQLEndpointConfig.(SPARQLEndpointConfig.java:50)
at org.cytoscape.vsdl3c.internal.CyActivator.start(CyActivator.java:75)
at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
at org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2064)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)
at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)
at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:509)
at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)
at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)

The workaround referenced here works: https://github.com/sgtp/SemScape/issues/6
    Workaround: Remove the framework/lib/endorsed/xercesImpl-2.11.0.jar file from the Cytoscape installation. It does not seem to effect the Cytoscape application and now the SemScape app functions.

**Comment by matthiaskoenig** [comment]
Current discussion
https://groups.google.com/forum/#!topic/cytoscape-app-dev/QpjgPR62ZK8
