### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by stuppie** [stuppie/WikiDataScape#3]
launched empty and add entrez gene 1107

currValues: [NM_001005271]
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at org.cytoscape.model.internal.AbstractTableFacade.getFacadeColumns(AbstractTableFacade.java:136)
at org.cytoscape.model.internal.AbstractTableFacade.getColumns(AbstractTableFacade.java:131)
at org.cytoscape.browser.internal.view.BrowserTableModel.getRowCount(BrowserTableModel.java:130)
at javax.swing.JTable$ModelChange.<init>(JTable.java:4086)
at javax.swing.JTable.sortedTableChanged(JTable.java:4104)
at javax.swing.JTable.tableChanged(JTable.java:4395)
at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
at org.cytoscape.browser.internal.view.BrowserTableModel.fireTableChanged(BrowserTableModel.java:268)
at javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:198)
at org.cytoscape.browser.internal.view.BrowserTableModel.fireTableDataChanged(BrowserTableModel.java:254)
at org.cytoscape.browser.internal.view.BrowserTableModel$2.run(BrowserTableModel.java:259)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
currValues: [7816078]
currValues: [ENST00000330494]
nodeProps: {Node suid: 64=[<name: 'subclass of', id: 'P279>, <name: 'encodes', id: 'P688>, <name: 'ortholog', id: 'P684>, <name: 'strand orientation', id: 'P2548>, <name: 'found in taxon', id: 'P703>, <name: 'chromosome', id: 'P1057>]}

**Comment by stuppie** [comment]
Can't replicate...
Probably coming from NodeLookupTask::updateNodeTable
